
global:
  marketplace-ami: false
  owner: rflather@tibco.com
  qsname: quickstart-tibco-ems
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  amazon-linux:
    template_file: tibco-ems-master.template
    parameter_input: amazon-linux-params.json
    regions:
      - us-east-1
      - us-east-2
      - us-west-2
      - eu-west-1
      - ap-southeast-2
      - eu-central-1
      # Testing EFS Region rule. This should fail as EFS is not supported in us-west
      #- us-west-1
  redhat-linux:
    template_file: tibco-ems-master.template
    parameter_input: redhat-linux-params.json
    regions:
      - us-east-1
      - us-east-2
      - us-west-2
      - eu-west-1
      - ap-southeast-2
      - eu-central-1
      #- us-west-1       # Testing EFS Region rule. This should fail as EFS is not supported in us-west-1
